spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test2?characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8082
#spring:
#  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 1023615397@qq.com
    #QQ邮箱的授权码
    password: skhszfebtxjqbfgg
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #freemarker配置
  freemarker:
    content-type: text/html
    #后缀名
    suffix: .ftl
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
  # Active Profile Settings




#设置一个邮件发送人
lance:
  mail:
    sender: 1023615397@qq.com

